PDG Implementation
spgroup/conflict-static-analysis pull request #50
Opened 2022-05-24 20:21 UTC by galilasmb

2022-06-20 21:02 UTC, barbosamaatheus requested changes

2022-06-20 21:02 UTC, barbosamaatheus commented on time.txt
> +1,96800
de que se trata esse arquivo?

2022-06-20 21:02 UTC, barbosamaatheus commented on src/test/java/br/unb/cic/analysis/cda/CDTest.java
> +//import br.unc.cic.analysis.test.DefinitionFactory;
Todo comentado?

2022-06-20 21:02 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/svfa/confluence/ConfluenceConflict.java
> +import br.ufpe.cin.soot.graph.LambdaNode;
Porque essa troca?

2022-06-20 21:02 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/cda/CDAInterProcedural.java
> +//package br.unb.cic.analysis.cda;
Todo comentado?

2022-06-20 21:02 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/Main.java
> +        analysis.buildFlowGraph();
Porque vc está trocando esse metodo?

2022-06-20 21:02 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/Main.java
> +//    private void runCDAnalysis(String classpath) {
Todo comentado?

2022-06-20 21:02 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/Main.java
> +//            CommandLine cmd = parser.parse(m.options, args);
remover

2022-06-28 12:04 UTC, galilasmb commented on time.txt
> +1,96800
Esse foi da execução de meu experimento. Calculando o tempo de execução.

2022-06-28 12:05 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/svfa/confluence/ConfluenceConflict.java
> +import br.ufpe.cin.soot.graph.LambdaNode;
Porque era o pacote da UNB e criei um pra UFPE.

2022-06-28 12:05 UTC, galilasmb commented on src/test/java/br/unb/cic/analysis/cda/CDTest.java
> +//import br.unc.cic.analysis.test.DefinitionFactory;
Era para o projeto somente de CD. Como criei um que engloba CD, tive que comentar pra não dar conflito. Mas nas próximas versões mudarei isto. Pois estamos mudando a arquitetura.

2022-06-28 12:05 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/cda/CDAInterProcedural.java
> +//package br.unb.cic.analysis.cda;
Era para o projeto somente de CD. Como criei um que engloba CD, tive que comentar pra não dar conflito. Mas nas próximas versões mudarei isto. Pois estamos mudando a arquitetura.

2022-06-28 12:06 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/Main.java
> +        analysis.buildFlowGraph();
Alterei o método por conta de outras análises, não era SVF somente.

2022-06-28 12:06 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/Main.java
> +//    private void runCDAnalysis(String classpath) {
Era para o projeto somente de CD. Como criei um que engloba CD, tive que comentar pra não dar conflito. Mas nas próximas versões mudarei isto. Pois estamos mudando a arquitetura.

2022-07-29 17:18 UTC, galilasmb commented
@pauloborba e @barbosamaatheus fiz atualização para executar PDG com a nova arquitetura. Em resumo, DFP e CD ficaram iguais, apenas criei novas classes concretas para chamar suas respetivas análises. Já PDG, mudei para a arquitetura nova, resultando em um método que chama PDG e passa como parâmetro um DFP e CD.
runPDF(){
  pdg = new PDGConcreta();
  dfp = new DFPConcreta();
  cd = new CDConcreta();

  pdg.buildPDG(cd, dfp);
}

2022-08-01 18:51 UTC, pauloborba requested changes

2022-08-01 18:51 UTC, pauloborba commented on .settings/org.eclipse.jdt.core.prefs
> +eclipse.preferences.version=1
@galilasmb esse arquivo é algo específico do teu ambiente de trabalho? se for, não deveria ser colocado no repositório

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/AbstractMergeConflictDefinition.java
> +    private int omitExceptingUnitEdges; //1 - true and 2-false
@galilasmb não entendi porque isso aparece aqui. conceitualmente, o conflito não deveria ter informação de se ele foi gerado ou não considerando arestas de exceção

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +        int depthLimit = Integer.parseInt(cmd.getOptionValue("oaDepthLimit", "5"));
@galilasmb não seria melhor ter isso como uma opção de linha de comandos, já que podemos querer fazer experimentos com valores diferentes de profundidade? isso também pode gerar diferença em relação aos resultados que você já tinha @barbosamaatheus

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +        PDGSDGAnalysis analysis = new PDGSDGInterProcedural(classpath, definition);
@galilasmb repensar em todos esses nomes de análise se não seria Intra

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +    private void runPDGSDGAnalysis(String classpath) {
@galilasmb adiciona um comentário explicando o que se espera que seja passado como classpath

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +    public static long time;
@galilasmb não seria melhor private?

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
>      private ReachDefinitionAnalysis analysis;
@galilasmb ainda precisamos disso? precisa estar aqui?

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
>      private Set<String> targetClasses;
@galilasmb adiciona um comentário explicando o que é cada atributo desse

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +        analysis.buildPDG(cd, dfp);
@galilasmb para ser mais precisa, a medição de tempo não deveria ser logo após a detecção dos conflitos? cria pdg, descobre conflitos, para o tempo. e só depois voce transforma e imprime o dotModel, e as demais impressões. como impressão é caro, pode distorcer os valores medidos. @barbosamaatheus

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +        try {
@galilasmb merece um extract method

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +        analysis.buildPDG(cd, dfp);
o mesmo comentário vale para os métodos a seguir

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +        System.out.println(analysis.findSourceSinkPaths());
@galilasmb essas 3-4 linhas parecem merecer um extract também. parece uma duplicação do que temos no método anterior

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +        analysis.buildCD();
@galilasmb os comentários acima devem se aplicar aqui também

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/cd/CDAnalysis.java
> + * An analysis wrapper around the Sparse value
@galilasmb isso não está correto, certo? coloca um comentário explicando a análise e o nome dela

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/cd/CDAnalysis.java
> +        //TODO: what is the role of soot classPath here??
?

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/cd/CDInterProcedural.java
> +public class CDInterProcedural extends CDAnalysis {
@galilasmb não entendi porque precisa dessa classe. como ela não acrescenta nada à superclasse, não deveria existir

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/dfp/DFPAnalysis.java
> +import java.util.stream.Collectors;
@galilasmb no diretório principal, linkado no README, deveria ter um diagrama de classe com as principais classes

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/dfp/DFPAnalysis.java
> +        //TODO: what is the role of soot classPath here??
?

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/dfp/DFPAnalysis.java
> +    public final scala.collection.immutable.List<SootMethod> getEntryPoints() {
@galilasmb ainda parece haver uma certa duplicação de código que talvez possa ser evitada em uma próxima versão

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/dfp/DFPInterProcedural.java
> +    public boolean interprocedural() {
@galilasmb para PDG, deveria ser intra, não?

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/pdgsdg/PDGSDGAnalysis.java
> +    private AbstractMergeConflictDefinition definition;
@galilasmb adiciona um comentário explicando qual o propósito disso e porque é necessário... já que nas outras classes similares a essa não temos isso

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/pdgsdg/PDGSDGInterProcedural.java
> +    public boolean interprocedural() {
@galilasmb verificar também. não sei se faz sentido

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/svfa/SVFAIntraProcedural.java
> +        return false;
@galilasmb adiciona comentário explicando porque. os outros estão como true mas tem que mudar também para false porque PDG é intra?

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/svfa/confluence/ConfluenceConflict.java
> +import br.ufpe.cin.soot.graph.LambdaNode;
@galilasmb mas a gente quer mesmo duplicar a classe? por que não continuamos usando a dependência da UnB?

2022-08-01 18:51 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/svfa/confluence/SVFAConfluenceAnalysis.java
> +            public boolean propagateObjectTaint() {
@galilasmb por que essas mudanças?

2022-08-01 18:51 UTC, pauloborba commented on time.txt
> +1,96800
@galilasmb como é um resultado de execução, não deveria ser incluído no repo

2022-08-01 18:51 UTC, pauloborba commented on src/test/java/br/unb/cic/analysis/svfa/SVFATest.java
> +        Assert.assertEquals(1, analysis.svg().reportConflicts().size());
@galilasmb as modificações aqui sugerem que analysis deveria ter o seu reportConflicts, que internamente conhece essa lógica de chamar o svg(). assim evitaria repetir a lógica aqui para cada teste

2022-08-01 18:51 UTC, pauloborba commented on src/test/java/br/unb/cic/analysis/samples/PDGSDGSample.java
> +package br.unb.cic.analysis.samples;
@galilasmb esse arquivo é igual ao anterior?

2022-08-01 18:51 UTC, pauloborba commented on src/test/java/br/unb/cic/analysis/pdgsdg/PDGSDGTest.java
> +    public CDAnalysis configureIntraTestCD(String classpath, int[] leftchangedlines, int[] rightchangedlines) {
@galilasmb intra e inter misturados aí nos nomes das declaraçÕes

2022-08-01 20:00 UTC, barbosamaatheus requested changes

2022-08-01 20:00 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/Main.java
> +        int depthLimit = Integer.parseInt(cmd.getOptionValue("oaDepthLimit", "5"));
@pauloborba isso já é um opção de linha de comando. "oaDepthLimit" é a opção e nesse caso 5 é o valor default caso a opção não seja enviada. 

Normalmente, em nossas execuções, estamos usando 5 para oaDepthLimit. Mas o padrão anterior que havia combinado com o senhor no momento da implementação era de 10. 

Acredito que deixar em 5 não vai afetar em nada uma vez que já é o valor que normalmente usamos e se precisarmos mudar, basta passar a opção via linha de comando.

2022-08-01 20:00 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/Main.java
> +        analysis.buildPDG(cd, dfp);
@pauloborba e @galilasmb na análise de OA eu faço a medição na própria classe da análise.

2022-08-01 20:00 UTC, barbosamaatheus commented on .settings/org.eclipse.jdt.core.prefs
> +eclipse.preferences.version=1
Acredito que esse arquivo deveria estar no .gitignore. Verifica por favor.

2022-08-01 20:00 UTC, barbosamaatheus commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
Do que se trata esse arquivo? é algo do teu ambiente? Se for, não deveria ter subido pro remoto, coloca no gitignore.

2022-08-01 20:00 UTC, barbosamaatheus commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
Mesma coisa. "Do que se trata esse arquivo? é algo do teu ambiente? Se for, não deveria ter subido pro remoto, coloca no gitignore. "

2022-08-01 20:00 UTC, barbosamaatheus commented on soot-analysis.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Aqui tambem: "Do que se trata esse arquivo? é algo do teu ambiente? Se for, não deveria ter subido pro remoto, coloca no gitignore. "

2022-08-02 20:03 UTC, galilasmb commented on time.txt
> +1,96800
Certo, inserido no gitignore

2022-08-02 20:04 UTC, galilasmb commented on src/test/java/br/unb/cic/analysis/cda/CDTest.java
> +//import br.unc.cic.analysis.test.DefinitionFactory;
Resolvido.

2022-08-02 20:05 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/svfa/confluence/ConfluenceConflict.java
> +import br.ufpe.cin.soot.graph.LambdaNode;
Ainda não é a versão final, quando Rodrigo finalizar a release, precisaremos trocar estas questões de pacotes.

2022-08-02 20:05 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/cda/CDAInterProcedural.java
> +//package br.unb.cic.analysis.cda;
Resolvido.

2022-08-02 20:05 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/Main.java
> +        analysis.buildFlowGraph();
Resolvido.

2022-08-02 20:05 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/Main.java
> +//    private void runCDAnalysis(String classpath) {
Resolvido.

2022-08-02 20:05 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/Main.java
> +//            CommandLine cmd = parser.parse(m.options, args);
Removido.

2022-08-10 18:15 UTC, pauloborba approved these changes

2022-08-11 20:39 UTC, barbosamaatheus approved these changes

2022-08-11 20:41 UTC, merged