fix: filter conflicts with the same root
spgroup/conflict-static-analysis pull request #51
Opened 2022-06-21 02:37 UTC by barbosamaatheus

this fixes the error that was causing `ConcurrentModificationException`

2022-06-24 16:27 UTC, pauloborba requested changes

2022-06-24 16:27 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/ioa/InterproceduralOverrideAssignment.java
> +        for(Conflict conflict: conflictsResults){
@barbosamaatheus testa o caso em que conflictsResults tem apenas dois conflitos, os dois com o mesmo source e target. esse código vai retornar conflictsFilter vazio?

2022-06-27 15:47 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/ioa/InterproceduralOverrideAssignment.java
> +        for(Conflict conflict: conflictsResults){
Professor, já temos um teste para isso: https://github.com/spgroup/conflict-static-analysis/blob/develop/src/test/java/br/unb/cic/analysis/samples/ioa/StacktraceConflictSample.java

Ao executar o teste o log mostra apenas um conflito: 
`[source(br.unb.cic.analysis.samples.ioa.StacktraceConflictSample, bar, 21, this.<br.unb.cic.analysis.samples.ioa.StacktraceConflictSample: int x> = 2, 
[Stacktrace{sootClass=StacktraceConflictSample, sootMethod=void main(), lineNumber=11}, 
Stacktrace{sootClass=StacktraceConflictSample, sootMethod=void bar(), lineNumber=21}]) => 
sink(br.unb.cic.analysis.samples.ioa.StacktraceConflictSample, qux, 26, this.<br.unb.cic.analysis.samples.ioa.StacktraceConflictSample: int x> = 3, 
[Stacktrace{sootClass=StacktraceConflictSample, sootMethod=void main(), lineNumber=10}, 
Stacktrace{sootClass=StacktraceConflictSample, sootMethod=void foo(), lineNumber=15}, 
Stacktrace{sootClass=StacktraceConflictSample, sootMethod=void qux(), lineNumber=26}])]`

Ja o arquivo out.txt grava 2 conflitos mas os dois tem o mesmo source. 
Segue arquivo out em anexo.

Ou seja, é detectado dois conflitos que são reportados pro completo no out.txt mas o log mostra apenas um conflito pois os dois conflitos tem a mesma linha causadora. 


[out.txt](https://github.com/spgroup/conflict-static-analysis/files/8993419/out.txt)

2022-07-01 21:37 UTC, pauloborba approved these changes

2022-07-05 19:38 UTC, galilasmb approved these changes

2022-07-05 20:23 UTC, merged