Add Point to
spgroup/conflict-static-analysis pull request #59
Opened 2022-10-27 20:08 UTC by barbosamaatheus

2022-11-01 13:36 UTC, pauloborba requested changes

2022-11-01 13:36 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/ioa/InterproceduralOverrideAssignment.java
adicionar comentário

2022-11-01 13:36 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/ioa/InterproceduralOverrideAssignment.java
> +            return compareSignature(fromDataFlowAbstraction.getFieldRef(), fromValue.getFieldRef())
verificar se um OR se aplicaria: expressões são textualmente iguais OU (a assinatura do atributo é textualmente igual E variáveis podem apontar para o mesmo objeto)

verificar teste: m(p1, p2) {p1.x=...;...;p2.x=...} 

m(p1, p2) {p1.x=...;...;p1.x=...}

m(p1, p2) {p1.x=...;p1=p2; p1.x=...}

m(p1, p2) {p1.x=...;p1=new P(); p1.x=...}


verificar teste: main{m(new P(),new P());} m(p1, p2) {p1.x=...;...;p2.x=...} m entry point => OA, main entry point => NO OA

2022-11-01 13:36 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/ioa/InterproceduralOverrideAssignment.java
> +            return compareSignature(fromDataFlowAbstraction.getFieldRef(), fromValue.getFieldRef())
apenas para expressoes do tipo o.a? 

e para arrays? a[i] 

a[0]=5;... b=a; ....b[0]=6;

tem mais tipos de expressões?

2022-11-03 13:58 UTC, galilasmb approved these changes

2022-11-07 18:01 UTC, pauloborba approved these changes

2022-11-07 18:02 UTC, merged