fix: add to path direction in toString
spgroup/conflict-static-analysis pull request #60
Opened 2022-11-03 13:58 UTC by galilasmb

1. Add path direciton in toString
2. Add a new test using Hashmap

2022-11-03 19:38 UTC, pauloborba requested changes

2022-11-03 19:38 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +    public void saveTimeExecution(long start){
saveExecutionTime

2022-11-07 17:51 UTC, barbosamaatheus approved these changes

2022-12-16 13:44 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/Main.java
> +    public void saveTimeExecution(long start){
Feito, pode mergear.

2022-12-16 14:07 UTC, merged