Develop
spgroup/conflict-static-analysis pull request #63
Opened 2023-01-04 13:05 UTC by barbosamaatheus

2023-01-04 13:12 UTC, pauloborba requested changes

2023-01-04 13:12 UTC, pauloborba commented on docker/Dockerfile
> +RUN cd /home/miningframework/output/files && git checkout article2023
@barbosamaatheus dá dois checkouts mesmo no projeto do mining? é necessário?

2023-01-04 19:39 UTC, barbosamaatheus commented on docker/Dockerfile
> +RUN cd /home/miningframework/output/files && git checkout article2023
@pauloborba na verdade esse é o caminho para o mergedataset. O clone do mergedataset foi feito para dentro de output/files dentro do miningframework

2023-01-04 19:46 UTC, pauloborba commented
Hum, entendi.

Esquisito porque o dataset vai ser input para o processo, mas aparece dentro de output.

Vamos deixar assim agora, mas adiciona um comentário explicando, por favor

> On 4 Jan 2023, at 16:39, Matheus Barbosa ***@***.***> wrote:
> 
> 
> @barbosamaatheus commented on this pull request.
> 
> In docker/Dockerfile <https://github.com/spgroup/conflict-static-analysis/pull/63#discussion_r1061823655>:
> 
> >  ## 3 - Choose mergedataset version
> -RUN cd /home/miningframework/output/files && git checkout TAG_BRANCH_OR_COMMIT_REFS # EG: git checkout develop
> +RUN cd /home/miningframework/output/files && git checkout article2023
> @pauloborba <https://github.com/pauloborba> na verdade esse é o caminho para o mergedataset. O clone do mergedataset foi feito para dentro de output/files dentro do miningframework
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/spgroup/conflict-static-analysis/pull/63#discussion_r1061823655>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAJGYJBNKYHERC4EQ3PQEJLWQXGXTANCNFSM6AAAAAATQYXTGI>.
> You are receiving this because you were mentioned.
>

2023-01-05 13:13 UTC, pauloborba approved these changes

2023-01-05 14:54 UTC, galilasmb approved these changes

2023-01-10 20:35 UTC, merged