feat: update dockerfile and instrutions
spgroup/conflict-static-analysis pull request #64
Opened 2023-01-24 22:04 UTC by barbosamaatheus

2023-01-30 18:47 UTC, galilasmb approved these changes

2023-01-31 16:53 UTC, pauloborba requested changes

2023-01-31 16:53 UTC, pauloborba commented on docker/Dockerfile
> +# Intall Requeriments
@barbosamaatheus o certo é Install Requirements

mas senti falta de uma explicação do que é esse requirements, qual o propósito.

2023-01-31 16:53 UTC, pauloborba commented on docker/Dockerfile
> +# Run Build Union Script
@barbosamaatheus Build Union Script? o que é isso? não está claro

2023-01-31 21:58 UTC, barbosamaatheus commented on docker/Dockerfile
> +# Intall Requeriments
Podemos dizer que isso faz parte do build do mining framework. No readme do projeto temos a explicação: 

> For one of the implementation of the postprocessing variability point ([OutputProcessorImpl](https://github.com/spgroup/miningframework/tree/master/src/services/OutputProcessorImpl.groovy)), you also have to install [Python](https://www.python.org/) version 3.7.x or newer. This is needed for a script that fetches build files from Github, and another script that converts collected data to a format that is used by the SOOT static analyses invoked by this instantiation. You may need to install dependencies for Python scripts. Once you have Python 3 installed, run pip3 install -r requirements.txt


Basicamente instala algumas dependências python no projeto. Precisamos instalar, pois a geração do PDF com os resultados implementada por galileu usa python e algumas dessas dependências.

2023-01-31 22:01 UTC, barbosamaatheus commented on docker/Dockerfile
> +# Run Build Union Script
Esse é um script implementado por Galileu para unir os .jar que são muito grandes. No readme do [mergedateset ](https://github.com/spgroup/mergedataset#build-union-script) temos a  seguinte explicação: 

> Some build files are larger than 100 MB, not supported by Github, so they were separated using split, to union them, run the script located at the root with the following command ...

O nome da seção do readme é Build Union Script, por isso usei o mesmo nome aqui. Não achei que era necessário copiar a explicação mais uma vez no docker, pois isso faz parte do "Build" do mergedataset

2023-01-31 22:24 UTC, pauloborba approved these changes

2023-01-31 22:24 UTC, merged