feat: save time execution
spgroup/conflict-static-analysis pull request #67
Opened 2023-02-16 18:59 UTC by galilasmb

2023-02-17 18:04 UTC, pauloborba requested changes

2023-02-17 18:04 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +        saveExecutionTime("Configure Soot OA Inter");
@galilasmb e @barbosamaatheus isso não seria após os dois comandos a seguir?

2023-02-17 18:04 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +        saveExecutionTime("Time to perform SVFA");
DF, não SVFA

2023-02-17 18:04 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +        saveExecutionTime("Time to perform SVFA");
agora, para efeito de depuração, poderia quebrar ainda mais aí, em três partes, se necessário: CONFIGURESOOT, CREATEGRAPH, RUNANALYSIS

2023-02-22 19:14 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/Main.java
> +        saveExecutionTime("Configure Soot OA Inter");
o applyPackages vai executar a análise.  Então acredito que seria na linha superior a esse comando.

2023-02-28 20:47 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/Main.java
> +        saveExecutionTime("Time to perform SVFA");
Paulo, não dá pra fazer isso, porque é feito na análise de Rodrigo.

2023-03-06 13:59 UTC, barbosamaatheus approved these changes

2023-03-07 14:57 UTC, merged