fix: resolve error with configure Soot
spgroup/conflict-static-analysis pull request #68
Opened 2023-03-08 20:59 UTC by galilasmb

2023-03-09 21:06 UTC, pauloborba requested changes

2023-03-09 21:06 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/pdg/PDGAnalysisSemanticConflicts.java
>      }
@galilasmb tá tirando java.util de tudo? a ideia não seria justamente ajustar o código para não dar problema mesmo com java.util? @barbosamaatheus em OA adicionas que pacotes?

2023-03-15 13:44 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/pdg/PDGAnalysisSemanticConflicts.java
>      }
Atualmente OA usa java.util.*

2023-03-15 13:44 UTC, barbosamaatheus approved these changes

2023-03-22 00:44 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/pdg/PDGAnalysisSemanticConflicts.java
>      }
@galilasmb isso que comentei hoje!

2023-04-25 13:59 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/pdg/PDGAnalysisSemanticConflicts.java
>      }
A ideia é que todos não usem java.util, não?

2023-04-25 13:59 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/pdg/PDGAnalysisSemanticConflicts.java
>      }
Todos usem ou só deixar OA com isso?

2023-04-25 14:01 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/pdg/PDGAnalysisSemanticConflicts.java
>      }
Deixei só OA conforme original.

2023-04-26 12:32 UTC, pauloborba approved these changes

2023-04-26 12:32 UTC, merged