chore: updating README
spgroup/conflict-static-analysis pull request #76
Opened 2023-04-26 13:40 UTC by galilasmb

2023-04-26 13:46 UTC, pauloborba requested changes

2023-04-26 13:46 UTC, pauloborba commented on docker/README.md
> +`chmod +x script.sh
@galilasmb vamos usar um nome mais intuitivo ao invés de script.sh

2023-04-26 13:46 UTC, pauloborba commented on docker/README.md
> +./run_experiment.sh`
@galilasmb também achei esquisito o nome run_experiment.sh. isso roda o experimento uma única vez ou 10 vezes? o nome dá a entender que só uma vez

explica também que roda 10 vezes para medir tempo de execução

2023-04-26 14:15 UTC, galilasmb commented on docker/README.md
> +./run_experiment.sh`
Alterei a descrição.

2023-04-26 14:15 UTC, barbosamaatheus requested changes

2023-04-26 14:15 UTC, barbosamaatheus commented on docker/README.md
> +## Running the experiment 10 (ten) times
Revisa o titulo

2023-04-26 14:16 UTC, galilasmb commented on docker/README.md
> +## Running the experiment 10 (ten) times
Feito

2023-04-26 14:16 UTC, barbosamaatheus approved these changes

2023-04-26 14:17 UTC, galilasmb commented on docker/README.md
> +`chmod +x script.sh
Alterei.

2023-04-27 12:29 UTC, pauloborba approved these changes

2023-04-27 12:29 UTC, merged