Experiment Version
spgroup/conflict-static-analysis pull request #79
Opened 2023-07-24 16:50 UTC by galilasmb

2023-07-24 19:00 UTC, barbosamaatheus requested changes

2023-07-24 19:00 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/Main.java
> +        System.out.println("Visited methods: "+ interproceduralOverrideAssignment.getVisitedMethods());
Isso aqui são logs? Devem está na versão final?

2023-07-24 19:00 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/ioa/InterproceduralOverrideAssignment.java
> +        System.out.println(String.format("%s", "CONFLICTS: " + filterConflictsWithSameRoot(getConflicts())));
pq removeu o log pra por system.out?

2023-07-25 00:04 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/Main.java
> +        System.out.println("Visited methods: "+ interproceduralOverrideAssignment.getVisitedMethods());
Sim, estamos criando uma planilha final com os métodos visitados por cada análise, por isso isso está aqui.

2023-07-25 00:05 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/Main.java
> +        System.out.println("Visited methods: "+ interproceduralOverrideAssignment.getVisitedMethods());
Verdade, vou remover. Já está salvando tudo na linha abaixo. Obrigado.

2023-07-25 00:07 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/Main.java
> +        System.out.println("Visited methods: "+ interproceduralOverrideAssignment.getVisitedMethods());
Isso, a gente está pegando de acordo com o log os métodos visitados por cada análise e criando uma planilha.

2023-07-25 00:07 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/Main.java
> +        System.out.println("Visited methods: "+ interproceduralOverrideAssignment.getVisitedMethods());
Deixando isso no log de execução, teremos uma segurança maior para double check da execução final.

2023-07-25 00:08 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/ioa/InterproceduralOverrideAssignment.java
> +        System.out.println(String.format("%s", "CONFLICTS: " + filterConflictsWithSameRoot(getConflicts())));
Pra ficar igual a todos na saída padrão. Só OA estava como LOG.

2023-07-25 01:17 UTC, galilasmb commented on pom.xml
> +			<version>0.4.35</version>
Atualizando para a última versão executada.

2023-07-25 01:17 UTC, galilasmb commented on pom.xml
> +			<version>0.4.5</version>
Atualizando para última versão executada.

2023-07-25 01:18 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/AbstractMergeConflictDefinition.java
> +            for(Statement actual_stmt: statements) {
Percorre todas os statements e checa se é chamada de um método, então cria e adiciona a lista de métodos visitados até aqui para chegar neste statement

2023-07-25 01:18 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/AbstractMergeConflictDefinition.java
> +    private Statement getGeneratedStatementFromUnitWithTraversedLine(Statement  actual_stmt, Stmt unit_from_stmt, Statement.Type type){
Retorna o statement com a sua lista de métodos visitados até então

2023-07-25 01:56 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/AbstractMergeConflictDefinition.java
> +                traversedLine_list.add(traversedLine_from_invokeStmt);
Isso cria um statement, usa a parte criada já por Matheus em OA para inserir a lista de métodos visitadas até este stement e dá um set no atributo traverseLine para o caso de InvokeStmt.

2023-07-25 01:56 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/AbstractMergeConflictDefinition.java
> +                        res.addAll(traverse(stmt_from_unit.getInvokeExpr().getMethod(), traversed, actual_traversedLine, type, level));
Isso cria um statement, usa a parte criada já por Matheus em OA para inserir a lista de métodos visitadas até este stement e dá um set no atributo traverseLine para o caso de InvokeExp.

2023-07-25 01:57 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/AbstractMergeConflictDefinition.java
> +                    res.addAll(traverse(assignStmt.getInvokeExpr().getMethod(), traversed, actual_traversedLine, type, level));
Isso cria um statement, usa a parte criada já por Matheus em OA para inserir a lista de métodos visitadas até este stement e dá um set no atributo traverseLine para o caso de InvokeExp de uma definição de Sink.

Essa parte do IF já existia no algoritmo anteriormente, apenas fiz adicionar a parte de métodos e set do statement atual.

if(type.equals(Statement.Type.SOURCE) && u instanceof AssignStmt) {
else if(type.equals(Statement.Type.SINK) && u.getUseBoxes().size() > 0) {

2023-07-25 11:51 UTC, barbosamaatheus approved these changes

2023-07-25 13:29 UTC, pauloborba approved these changes

2023-07-25 13:29 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/AbstractMergeConflictDefinition.java
> +                        SootMethod aux_m = s.getSootMethod();
extract method?

2023-07-25 13:29 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/AbstractMergeConflictDefinition.java
> +                        SootMethod aux_m = s.getSootMethod();
daria para pegar de stmt?

2023-07-25 13:29 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/AbstractMergeConflictDefinition.java
> +                        TraversedLine aux_l = new TraversedLine(s.getSootMethod().getDeclaringClass(), s.getSootMethod().method(), stmt.getJavaSourceStartLineNumber());
rename

2023-07-25 13:29 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/AbstractMergeConflictDefinition.java
> +                        List<TraversedLine> aux_traversedLine =new ArrayList<>();
melhor tirar?

2023-07-25 13:29 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/AbstractMergeConflictDefinition.java
> +                SootMethod sm_aux = invokeStmt.getInvokeExpr().getMethod();
tirar tudo isso?

2023-07-25 13:29 UTC, merged