Adjusting report conflicts
spgroup/conflict-static-analysis pull request #80
Opened 2023-08-15 12:08 UTC by galilasmb

2023-09-29 14:44 UTC, pauloborba requested changes

2023-09-29 14:44 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +        boolean depthMethodsVisited = Boolean.parseBoolean(cmd.getOptionValue("printDepthSVFA", "false"));
@galilasmb faltou explicar isso no README?

2023-09-29 14:45 UTC, pauloborba approved these changes

2023-09-29 14:46 UTC, barbosamaatheus requested changes

2023-09-29 14:46 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/Main.java
> +        System.out.println("Depth limit: "+interproceduralOverrideAssignment.getDepthLimit());
Precisa disso?

2023-09-29 14:46 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/Main.java
> +            type_analysis = "e";
o que significa isso? ficou meio abstrato demais aqui.

2023-09-29 14:48 UTC, pauloborba requested changes

2023-09-29 14:48 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/AbstractMergeConflictDefinition.java
> +                        List<TraversedLine> actual_traversedLine = new ArrayList<>();
@galilasmb não entendi. merece um extract

2023-09-29 14:48 UTC, pauloborba approved these changes

2023-09-29 14:49 UTC, pauloborba approved these changes

2023-09-29 14:51 UTC, pauloborba approved these changes

2023-09-29 14:52 UTC, pauloborba approved these changes

2023-09-29 14:52 UTC, pauloborba approved these changes

2023-09-29 14:55 UTC, pauloborba requested changes

2023-09-29 14:55 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +            type_analysis = "e";
@galilasmb com Excepting você quer dizer Exception?

2023-09-29 14:55 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +            type_analysis = "e";
merece um extract

2023-09-29 14:55 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/Main.java
> +        if (omitExceptingUnitEdges) {
mesmo problema aqui

2023-09-29 14:55 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/svfa/confluence/DFPConfluenceAnalysis.java
> +        String type_analysis;
@galilasmb o que a gente ganha com essa lógica sobre os nomes? não seria melhor evitar isso e colocar os nomes diretos?

2023-09-29 14:57 UTC, pauloborba approved these changes

2023-10-05 13:19 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/Main.java
> +        System.out.println("Depth limit: "+interproceduralOverrideAssignment.getDepthLimit());
Isso é pra ficar no LOG de execução.

2023-10-05 13:20 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/Main.java
> +            type_analysis = "e";
Que feio mesmo. Ajeitei.

2023-10-05 13:24 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/svfa/confluence/DFPConfluenceAnalysis.java
> +        String type_analysis;
A gente consegue identificar melhor nos logs qual análise foi reportada como erro. Antes não sabia se era Inter ou Intra, com ou sem exceção.

2023-10-05 13:25 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/AbstractMergeConflictDefinition.java
> +                        List<TraversedLine> actual_traversedLine = new ArrayList<>();
Esse é o algoritmo que o Matheus usou, inserindo a lista atravessada ao longo da execução, assim sabemos de onde veio para chegar a um determinado statement que gerou conflito.

2024-05-07 17:48 UTC, pauloborba commented
@galilasmb @barbosamaatheus está com conflitos

2024-05-08 17:39 UTC, galilasmb commented
Resolvido os conflitos, @pauloborba. Fiz com o Matheus, ele alterou algumas coisas na chamada de OA.

2024-05-08 17:49 UTC, barbosamaatheus approved these changes

2024-05-08 17:54 UTC, barbosamaatheus approved these changes

2024-05-08 18:17 UTC, Vinicius-resende-cin approved these changes

2024-05-09 00:14 UTC, pauloborba approved these changes

2024-05-09 00:14 UTC, merged