New oa version
spgroup/conflict-static-analysis pull request #82
Opened 2023-10-06 01:02 UTC by barbosamaatheus

- Ajustei a análise de OA baseado na nova versão da definição. 

> Dois desenvolvedores modificam o mesmo elemento de estado sem modificações de base nesse elemento de estado, entre eles.
> Quando um desenvolvedor altera um elemento de estado e, em seguida, outro desenvolvedor modifica um atributo de um objeto apontado por esse elemento de estado modificado anteriormente, o algoritmo de Análise de Fluxo de Dados é aplicado. Isso ocorre porque para modificar o atributo, é necessário primeiro acessar o objeto de destino por meio do valor de estado.
> Ocorre algo semelhante com arrays. Quando um desenvolvedor altera um elemento de estado, como um array, e outro desenvolvedor modifica apenas um índice desse mesmo array, o algoritmo de Análise de Fluxo de Dados é empregado. Isso acontece porque, para alterar o índice do array, é necessário primeiro acessar o array em questão por meio do estado modificado.

- Apliquei refatoração para deixa o código com uma melhor qualidade. 
- Com as modificações também corrigi a análise para passar alguns testes cases que não passavam antes.
- Adicionei @Ignore nos testes que fazem referência a relação de "containment", pois usaremos o algorítimo de DF assim como explicito na nova definição.

2023-11-09 18:31 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/Main.java
> +    private void runOverrideAssignmentAnalysis(String classpath, Boolean interprocedural) {
Boa, assim ficou melhor, padronizou com as outras análises que são inter e intra.

2023-11-09 18:32 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/model/Statement.java
> +	public PointsToSet getPointTo() {
Não seria melhor altrar o nome para getPointsTo?

2023-11-09 18:32 UTC, galilasmb commented on src/main/java/br/unb/cic/analysis/model/Statement.java
> +	public PointsToSet getPointTo() {
Por que nessa caso tá singular?

2023-11-09 18:34 UTC, galilasmb commented on src/test/java/br/unb/cic/analysis/df/ContainmentConflictTest.java
> +    private TaintedAnalysis analysis;
Por que TaintedAnalysis?

2023-11-09 18:34 UTC, galilasmb commented on src/test/java/br/unb/cic/analysis/df/ContainmentConflictTest.java
> +                res.put("br.unb.cic.analysis.samples.ioa.ContainmentSample", lines);
Padronizar os pacotes também, alterou o de cima de ioa para oa, mas aqui continuou igual.

2023-11-09 18:35 UTC, galilasmb commented on src/test/java/br/unb/cic/analysis/df/ContainmentConflictTest.java
> +                        analysis = new TaintedAnalysis(body, definition);
Não entendi o uso do TaitedAnalysis aqui

2023-11-09 18:36 UTC, galilasmb commented on src/test/java/br/unb/cic/analysis/df/ContainmentConflictTest.java
> +    private TaintedAnalysis analysis;
Ah, vi aqui que é de DF

2023-11-09 18:39 UTC, galilasmb approved these changes

2023-11-09 20:09 UTC, barbosamaatheus commented on src/test/java/br/unb/cic/analysis/df/ContainmentConflictTest.java
> +                res.put("br.unb.cic.analysis.samples.ioa.ContainmentSample", lines);
Esse é um caso de teste de DF que usava um sample de OA. Só mudei porque alterei o pacote onde os samples estão.

2023-11-10 14:37 UTC, barbosamaatheus commented on src/test/java/br/unb/cic/analysis/df/ContainmentConflictTest.java
> +                        analysis = new TaintedAnalysis(body, definition);
Eu apenas copiei de um caso de testes. A minha intenção aqui era executar DF com um semple de teste especifico.

2023-11-10 14:37 UTC, barbosamaatheus commented on src/test/java/br/unb/cic/analysis/df/ContainmentConflictTest.java
> +                        analysis = new TaintedAnalysis(body, definition);
Atualizei para usar DFP

2023-11-13 14:30 UTC, pauloborba requested changes

2023-11-13 14:30 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/model/Statement.java
> +	public PointsToSet getPointTo() {
também achei esquisito

2023-11-13 14:30 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/oa/OverrideAssignmentAbstraction.java
> +    public void remove(Statement stmt) {
@barbosamaatheus adiciona comentário. se for base retira das duas

2023-11-13 14:30 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/oa/OverrideAssignmentAbstraction.java
> +                this.getLeftAbstraction().add(element);
qual a vantagem de usar o get aqui ao invés de acessar o atributo direto?

2023-11-13 14:30 UTC, pauloborba commented on src/main/java/br/unb/cic/analysis/oa/TraversedMethodsWrapper.java
> +    private int visitedMethods = 0;
visitedMethods não seria o length da lista traversedMethods?

2023-12-06 19:04 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/oa/OverrideAssignmentAbstraction.java
> +                this.getLeftAbstraction().add(element);
Nesse caso, nenhum, foi só mania de desenvolvimento mesmo. Já atualizei

2023-12-06 19:22 UTC, barbosamaatheus commented on src/main/java/br/unb/cic/analysis/oa/TraversedMethodsWrapper.java
> +    private int visitedMethods = 0;
Não. visitedMethods  é uma contagem de todos os métodos que foram analisados. 
traversedMethods o método é removido da lista quando finaliza a sua analise. 

mudei para visitedMethodsCount

2023-12-08 20:34 UTC, pauloborba approved these changes

2023-12-08 20:34 UTC, merged