feat: add -entrypoints on readme
spgroup/conflict-static-analysis pull request #93
Opened 2024-07-04 19:16 UTC by barbosamaatheus

2024-07-04 19:22 UTC, Vinicius-resende-cin approved these changes

2024-07-04 20:45 UTC, pauloborba requested changes

2024-07-04 20:45 UTC, pauloborba commented on README.md
> +E.g.: `[org.example.Main:void main(java.lang.String[])]`
@barbosamaatheus que tal explicar o que acontece se não usar isso? a lista é separada por vírgulas?

2024-07-05 13:01 UTC, barbosamaatheus commented on README.md
> +E.g.: `[org.example.Main:void main(java.lang.String[])]`
Feito!

2024-07-05 16:43 UTC, Vinicius-resende-cin approved these changes

2024-07-09 16:52 UTC, galilasmb commented on pom.xml
> +			<url>https://maven.pkg.github.com/spgroup/svfa-scala/</url>
Temos que testar isso em um ambiente novo para saber se baixa todas as dependências corretamente. Localmente pode não ser bom porque já pode ter todas as dependências. Sugiro criar um docker para o experimento e rodar no servidor.

2024-07-09 16:53 UTC, galilasmb commented on pom.xml
> +			<version>0.5.10</version>
Rodrigo lançou uma nova versão? Vai utilizá-la? Cuidado nisso porque pode interferir em DF, PDG e Confluence.

2024-07-26 13:02 UTC, barbosamaatheus commented on pom.xml
> +			<version>0.5.10</version>
Estou usando a nova versão que gerei no repo do SVFA

2024-07-26 19:10 UTC, barbosamaatheus commented on pom.xml
> +			<url>https://maven.pkg.github.com/spgroup/svfa-scala/</url>
Fiz o teste em um contêiner vazio e funcionou.
![image](https://github.com/user-attachments/assets/54e3230c-5106-49e0-bcb4-beb07b5d65bd)

2024-07-29 16:21 UTC, pauloborba approved these changes

2024-07-29 16:22 UTC, merged